{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Failed to fetch synopsis for 'Mortal Kombat' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Eat Drink Man Woman' after 3 attempts.\n",
      "Failed to fetch synopsis for 'National Lampoon's Senior Trip' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Wonderful, Horrible Life of Leni Riefenstahl' after 3 attempts.\n",
      "Failed to fetch synopsis for 'In the Realm of the Senses' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Mission: Impossible' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The World of Apu' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Horseman on the Roof' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Spirits of the Dead' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Last Klezmer: Leopold Kozlowski, His Life and Music' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Wallace & Gromit: The Wrong Trousers' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Return of Martin Guerre' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Children Are Watching Us' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Double Life of Véronique' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Good, the Bad and the Ugly' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Wallace & Gromit: A Grand Day Out' after 3 attempts.\n",
      "Failed to fetch synopsis for 'My Life as a Dog' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The School of Flesh' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Howling II: ... Your Sister Is a Werewolf' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Mission' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Little Nemo: Adventures in Slumberland' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Black Cat, White Cat' after 3 attempts.\n",
      "Failed to fetch synopsis for 'A Fistful of Dollars' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Pokémon: The First Movie - Mewtwo Strikes Back' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Jonah Who Will Be 25 in the Year 2000' after 3 attempts.\n",
      "Failed to fetch synopsis for 'City of the Living Dead' after 3 attempts.\n",
      "Failed to fetch synopsis for 'For a Few Dollars More' after 3 attempts.\n",
      "Failed to fetch synopsis for 'With a Friend Like Harry...' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Garden of the Finzi-Continis' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Atanarjuat: The Fast Runner' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Woman Next Door' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Chopper Chicks in Zombietown' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Night of the Shooting Stars' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Triplets of Belleville' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Knife in the Water' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Passion of Joan of Arc' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Last Tango in Paris' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Nausicaä of the Valley of the Wind' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Diary of a Country Priest' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Reckoning' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Wages of Fear' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Master of the Flying Guillotine' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Spring, Summer, Fall, Winter... and Spring' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Hour of the Wolf' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Investigation of a Citizen Above Suspicion' after 3 attempts.\n",
      "Failed to fetch synopsis for 'A Short Film About Killing' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Testament of Dr. Mabuse' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Biggles: Adventures in Time' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Warriors of Heaven and Earth' after 3 attempts.\n",
      "Failed to fetch synopsis for 'House of Flying Daggers' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Boudu Saved from Drowning' after 3 attempts.\n",
      "Failed to fetch synopsis for 'When a Woman Ascends the Stairs' after 3 attempts.\n",
      "Failed to fetch synopsis for 'White Sun of the Desert' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Last Hurrah for Chivalry' after 3 attempts.\n",
      "Failed to fetch synopsis for 'A Chinese Ghost Story' after 3 attempts.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-11-28 18:28:37,268 CRITICAL [imdbpy] C:\\Users\\fugle\\AppData\\Roaming\\Python\\Python311\\site-packages\\imdb\\_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/find/?q=Daria+in+%27Is+It+Fall+Yet%3F%27&s=tt', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 405: 'Not Allowed'>},); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\fugle\\AppData\\Roaming\\Python\\Python311\\site-packages\\imdb\\parser\\http\\__init__.py\", line 233, in retrieve_unicode\n",
      "    response = uopener.open(url)\n",
      "               ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 525, in open\n",
      "    response = meth(req, response)\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 634, in http_response\n",
      "    response = self.parent.error(\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 563, in error\n",
      "    return self._call_chain(*args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 496, in _call_chain\n",
      "    result = func(*args)\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 643, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 405: Not Allowed\n",
      "2024-11-28 18:28:38,481 CRITICAL [imdbpy] C:\\Users\\fugle\\AppData\\Roaming\\Python\\Python311\\site-packages\\imdb\\_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/find/?q=Daria+in+%27Is+It+Fall+Yet%3F%27&s=tt', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 405: 'Not Allowed'>},); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\fugle\\AppData\\Roaming\\Python\\Python311\\site-packages\\imdb\\parser\\http\\__init__.py\", line 233, in retrieve_unicode\n",
      "    response = uopener.open(url)\n",
      "               ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 525, in open\n",
      "    response = meth(req, response)\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 634, in http_response\n",
      "    response = self.parent.error(\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 563, in error\n",
      "    return self._call_chain(*args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 496, in _call_chain\n",
      "    result = func(*args)\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 643, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 405: Not Allowed\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Failed to fetch synopsis for 'Kirikou and the Sorceress' after 3 attempts.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-11-28 18:28:39,752 CRITICAL [imdbpy] C:\\Users\\fugle\\AppData\\Roaming\\Python\\Python311\\site-packages\\imdb\\_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/find/?q=Daria+in+%27Is+It+Fall+Yet%3F%27&s=tt', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 405: 'Not Allowed'>},); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\fugle\\AppData\\Roaming\\Python\\Python311\\site-packages\\imdb\\parser\\http\\__init__.py\", line 233, in retrieve_unicode\n",
      "    response = uopener.open(url)\n",
      "               ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 525, in open\n",
      "    response = meth(req, response)\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 634, in http_response\n",
      "    response = self.parent.error(\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 563, in error\n",
      "    return self._call_chain(*args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 496, in _call_chain\n",
      "    result = func(*args)\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 643, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 405: Not Allowed\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Failed to fetch synopsis for 'Daria in 'Is It Fall Yet?'' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Sympathy for Mr. Vengeance' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Battles Without Honor and Humanity' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Sword of Doom' after 3 attempts.\n",
      "Failed to fetch synopsis for 'A Touch of Zen' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Man Who Planted Trees' after 3 attempts.\n",
      "Failed to fetch synopsis for 'March of the Penguins' after 3 attempts.\n",
      "Failed to fetch synopsis for 'American Pie Presents: Band Camp' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Sword of the Beast' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Voices of a Distant Star' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Lives of Others' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Youth of the Beast' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Tiger and the Snow' after 3 attempts.\n",
      "Failed to fetch synopsis for 'American Pie Presents: The Naked Mile' after 3 attempts.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-11-28 18:44:06,494 CRITICAL [imdbpy] C:\\Users\\fugle\\AppData\\Roaming\\Python\\Python311\\site-packages\\imdb\\_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/find/?q=Catch+and+Release&s=tt', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 405: 'Not Allowed'>},); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\fugle\\AppData\\Roaming\\Python\\Python311\\site-packages\\imdb\\parser\\http\\__init__.py\", line 233, in retrieve_unicode\n",
      "    response = uopener.open(url)\n",
      "               ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 525, in open\n",
      "    response = meth(req, response)\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 634, in http_response\n",
      "    response = self.parent.error(\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 563, in error\n",
      "    return self._call_chain(*args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 496, in _call_chain\n",
      "    result = func(*args)\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 643, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 405: Not Allowed\n",
      "2024-11-28 18:44:07,672 CRITICAL [imdbpy] C:\\Users\\fugle\\AppData\\Roaming\\Python\\Python311\\site-packages\\imdb\\_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/find/?q=Catch+and+Release&s=tt', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 405: 'Not Allowed'>},); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\fugle\\AppData\\Roaming\\Python\\Python311\\site-packages\\imdb\\parser\\http\\__init__.py\", line 233, in retrieve_unicode\n",
      "    response = uopener.open(url)\n",
      "               ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 525, in open\n",
      "    response = meth(req, response)\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 634, in http_response\n",
      "    response = self.parent.error(\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 563, in error\n",
      "    return self._call_chain(*args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 496, in _call_chain\n",
      "    result = func(*args)\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 643, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 405: Not Allowed\n",
      "2024-11-28 18:44:08,899 CRITICAL [imdbpy] C:\\Users\\fugle\\AppData\\Roaming\\Python\\Python311\\site-packages\\imdb\\_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/find/?q=Catch+and+Release&s=tt', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 405: 'Not Allowed'>},); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\fugle\\AppData\\Roaming\\Python\\Python311\\site-packages\\imdb\\parser\\http\\__init__.py\", line 233, in retrieve_unicode\n",
      "    response = uopener.open(url)\n",
      "               ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 525, in open\n",
      "    response = meth(req, response)\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 634, in http_response\n",
      "    response = self.parent.error(\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 563, in error\n",
      "    return self._call_chain(*args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 496, in _call_chain\n",
      "    result = func(*args)\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 643, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 405: Not Allowed\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Failed to fetch synopsis for 'Catch and Release' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Boss of It All' after 3 attempts.\n",
      "Failed to fetch synopsis for 'I'm a Cyborg, But That's OK' after 3 attempts.\n",
      "Failed to fetch synopsis for '4 Months, 3 Weeks and 2 Days' after 3 attempts.\n",
      "Failed to fetch synopsis for 'World on a Wire' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Welcome to the Sticks' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Sound of the Mountain' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Sword of the Stranger' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Neon Genesis Evangelion: Death & Rebirth' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Fullmetal Alchemist the Movie: Conqueror of Shamballa' after 3 attempts.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-11-28 18:56:43,486 CRITICAL [imdbpy] C:\\Users\\fugle\\AppData\\Roaming\\Python\\Python311\\site-packages\\imdb\\_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/find/?q=Daria+in+%27Is+It+College+Yet%3F%27&s=tt', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 405: 'Not Allowed'>},); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\fugle\\AppData\\Roaming\\Python\\Python311\\site-packages\\imdb\\parser\\http\\__init__.py\", line 233, in retrieve_unicode\n",
      "    response = uopener.open(url)\n",
      "               ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 525, in open\n",
      "    response = meth(req, response)\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 634, in http_response\n",
      "    response = self.parent.error(\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 563, in error\n",
      "    return self._call_chain(*args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 496, in _call_chain\n",
      "    result = func(*args)\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 643, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 405: Not Allowed\n",
      "2024-11-28 18:56:44,680 CRITICAL [imdbpy] C:\\Users\\fugle\\AppData\\Roaming\\Python\\Python311\\site-packages\\imdb\\_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/find/?q=Daria+in+%27Is+It+College+Yet%3F%27&s=tt', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 405: 'Not Allowed'>},); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\fugle\\AppData\\Roaming\\Python\\Python311\\site-packages\\imdb\\parser\\http\\__init__.py\", line 233, in retrieve_unicode\n",
      "    response = uopener.open(url)\n",
      "               ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 525, in open\n",
      "    response = meth(req, response)\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 634, in http_response\n",
      "    response = self.parent.error(\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 563, in error\n",
      "    return self._call_chain(*args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 496, in _call_chain\n",
      "    result = func(*args)\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 643, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 405: Not Allowed\n",
      "2024-11-28 18:56:45,963 CRITICAL [imdbpy] C:\\Users\\fugle\\AppData\\Roaming\\Python\\Python311\\site-packages\\imdb\\_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/find/?q=Daria+in+%27Is+It+College+Yet%3F%27&s=tt', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 405: 'Not Allowed'>},); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\fugle\\AppData\\Roaming\\Python\\Python311\\site-packages\\imdb\\parser\\http\\__init__.py\", line 233, in retrieve_unicode\n",
      "    response = uopener.open(url)\n",
      "               ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 525, in open\n",
      "    response = meth(req, response)\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 634, in http_response\n",
      "    response = self.parent.error(\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 563, in error\n",
      "    return self._call_chain(*args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 496, in _call_chain\n",
      "    result = func(*args)\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 643, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 405: Not Allowed\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Failed to fetch synopsis for 'Daria in 'Is It College Yet?'' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Blood of the Beasts' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Battlestar Galactica: The Plan' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Pekka ja Pätkä Suez'illa' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Castaway on the Moon' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Skin I Live In' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Headhunters' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Asterix and the Vikings' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Dragon Ball Z: The World's Strongest' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Dragon Ball Z: The Return of Cooler' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Dragon Ball Z: Super Android 13!' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Dragon Ball Z: Cooler's Revenge' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Dragon Ball Z: Bojack Unbound' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Dragon Ball Z: Broly - Second Coming' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Dragon Ball Z: Bio-Broly' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Take Aim at the Police Van' after 3 attempts.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-11-28 19:18:33,787 CRITICAL [imdbpy] C:\\Users\\fugle\\AppData\\Roaming\\Python\\Python311\\site-packages\\imdb\\_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/find/?q=42&s=tt', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 500: 'Internal Server Error'>},); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\fugle\\AppData\\Roaming\\Python\\Python311\\site-packages\\imdb\\parser\\http\\__init__.py\", line 233, in retrieve_unicode\n",
      "    response = uopener.open(url)\n",
      "               ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 525, in open\n",
      "    response = meth(req, response)\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 634, in http_response\n",
      "    response = self.parent.error(\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 563, in error\n",
      "    return self._call_chain(*args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 496, in _call_chain\n",
      "    result = func(*args)\n",
      "             ^^^^^^^^^^^\n",
      "  File \"c:\\ProgramData\\anaconda3\\Lib\\urllib\\request.py\", line 643, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 500: Internal Server Error\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Failed to fetch synopsis for 'The Break Up Man' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Jackass Presents: Bad Grandpa' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Evangelion: 3.0 You Can (Not) Redo' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Dragon Ball Z: Lord Slug' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Dragon Ball: The Path to Power' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Dance of Reality' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Man on High Heels' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Snowflake, the White Gorilla' after 3 attempts.\n",
      "Failed to fetch synopsis for 'A Pigeon Sat on a Branch Reflecting on Existence' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Wyrmwood: Road of the Dead' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Patlabor 2: The Movie' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Comedy Central Roast of James Franco' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Ghost in the Shell 2.0' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Nasu: Summer in Andalusia' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Boy and the Beast' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Blue Exorcist: The Movie' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Death Smiles on a Murderer' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Bremen Town Musicians' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Comedy Central Roast of David Hasselhoff' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Eiffel Tower Mystery' after 3 attempts.\n",
      "Failed to fetch synopsis for 'Der Herr Karl' after 3 attempts.\n",
      "Failed to fetch synopsis for 'The Night Is Short, Walk on Girl' after 3 attempts.\n",
      "Failed to fetch synopsis for 'No Game No Life: Zero' after 3 attempts.\n"
     ]
    }
   ],
   "source": [
    "from concurrent.futures import ThreadPoolExecutor, as_completed\n",
    "import pickle\n",
    "import time\n",
    "from imdb import IMDb\n",
    "\n",
    "with open('Movie_network.gpickle', 'rb') as f:\n",
    "    G_Movies = pickle.load(f)\n",
    "\n",
    "# Initialize IMDb object\n",
    "ia = IMDb()\n",
    "\n",
    "def reconstruct_title(char_list):\n",
    "    return \"\".join(char_list).strip()\n",
    "\n",
    "# Function to get synopsis (prefer cache, fallback to IMDbPY)\n",
    "def get_movie_synopsis(char_list):\n",
    "    # Reconstruct the title\n",
    "    title = reconstruct_title(char_list)\n",
    "    \n",
    "    # Fallback to IMDbPY\n",
    "    attempts = 0\n",
    "    while attempts < 3:\n",
    "        try:\n",
    "            movies = ia.search_movie(title)\n",
    "            if movies:\n",
    "                movie = movies[0]\n",
    "                ia.update(movie)  # Fetch full details\n",
    "                synopsis = movie.get('synopsis', [False])[0]\n",
    "                if synopsis:\n",
    "                    #make sure text does not have [] around it\n",
    "                    synopsis = synopsis.strip('[]')\n",
    "                    return synopsis\n",
    "                else:\n",
    "                    summary = movie.get('plot', [None])\n",
    "                    #make sure text does not have [] around it\n",
    "                    summary = summary[0].strip('[]') if summary else None\n",
    "                    if summary != None:\n",
    "                        return summary\n",
    "                    else:\n",
    "                        return summary, print(f\"No synopsis or summary found for '{title}'.\")\n",
    "            else:\n",
    "                return print(f\"No movie found for '{title}'.\")\n",
    "        except Exception as e:\n",
    "            attempts += 1\n",
    "            time.sleep(1)\n",
    "    return print(f\"Failed to fetch synopsis for '{title}' after 3 attempts.\")\n",
    "def fetch_synopsis(node_data):\n",
    "    title = node_data.get('title')\n",
    "    if title:\n",
    "        char_list = list(title)\n",
    "        return title, get_movie_synopsis(char_list)\n",
    "    return None\n",
    "\n",
    "#make nodes in graph only 100 first nodes\n",
    "#G_Movies = G_Movies.subgraph(list(G_Movies.nodes())[:100])\n",
    "\n",
    "# Use ThreadPoolExecutor to fetch synopses concurrently\n",
    "with ThreadPoolExecutor(max_workers=5) as executor:\n",
    "    futures = {executor.submit(fetch_synopsis, data): node for node, data in G_Movies.nodes(data=True)}\n",
    "\n",
    "    for future in as_completed(futures):\n",
    "        node = futures[future]\n",
    "        try:\n",
    "            result = future.result()\n",
    "            if result:\n",
    "                title, synopsis = result\n",
    "        except Exception as e:\n",
    "            print(f\"Error fetching synopsis for node {node}: {e}\")\n",
    "        # Store the synopsis in the node data\n",
    "        G_Movies.nodes[node]['synopsis'] = synopsis\n",
    "\n",
    "# Save the updated graph with synopses\n",
    "with open('Movie_network_with_synopses.gpickle', 'wb') as f:\n",
    "    pickle.dump(G_Movies, f)\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "anaconda-cloud": {},
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
